[DONT MERGE ME] typescript, promises, oh my!
stephenplusplus/split-array-stream pull request #1
Opened 2018-04-01 05:19 UTC by JustinBeckwith

![image](https://user-images.githubusercontent.com/534619/38170128-848d96a2-3531-11e8-8a3f-b2fa653d9a82.png)

This does a few things:
- Converts the module to TypeScript
- Eliminates the `async` dependency
- Converts the interface over to Promises instead of callbackies

It's waiting for a release of `is-stream-end` before we can merge. 

Feedback welcomed!

2018-04-01 22:49 UTC, stephenplusplus commented on package.json
> +    "is-stream-ended": "file:../is-stream-ended/is-stream-ended-0.1.3.tgz"
Published as 0.1.4

2018-04-01 22:51 UTC, stephenplusplus requested changes
Could you kill package-lock.json from this PR? I'm still not a big fan :(-- hoping it gets easier to work with as time goes, but it's still a big pain point for GC* at this time (and according to Google + StackOverflow, many others).

Feel free to add it to the new .gitignore :)

2018-04-01 23:31 UTC, JustinBeckwith commented on package.json
> +    "is-stream-ended": "file:../is-stream-ended/is-stream-ended-0.1.3.tgz"
Thank you!

2018-04-01 23:31 UTC, JustinBeckwith commented
Ooops, didn't even notice that got swooped up with the other changes.  Officially ignored :)

2018-04-02 12:51 UTC, stephenplusplus commented
Could you update the README as well?

2018-04-02 17:02 UTC, stephenplusplus approved these changes

2018-04-02 17:02 UTC, merged

2018-04-02 17:02 UTC, stephenplusplus commented
Thanks!

2018-04-02 17:04 UTC, stephenplusplus commented
Published as 2️⃣💠0️⃣💠0️⃣